config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :publications

  get 'main/index'

  get 'main/somos'

  get 'main/contacto'

  root 'main#index'

  get 'mypublications' => 'main#mypublications'

  get 'publicof/:user_id' => 'main#publicof', :as => "publicof"

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	validates :title, presence:true
	validates :photo, presence:true
	validates :address, presence:true
	validates :description, presence:true

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :publications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def somos
  end

  def contacto
  end

  def mypublications
  	@publications = current_user.publications
  end
  
  def publicof
  	@user_id = params[:user_id]
  	@user = User.find(@user_id)
  	@publications = @user.publications
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :index, :show]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :photo, :address, :description, :telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xml:lang="es" lang="es">
<head>
	<title>Pinterest</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.2.3/masonry.pkgd.min.js"></script>
	
</head>
<body>
	<%= render 'shared/navbar' %> 
	
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/main/contacto.html.erb
<h1>Main#contacto</h1>
<p>Find me in app/views/main/contacto.html.erb</p>

app/views/main/index.html.erb
<div class="container col-md-12">
	<div class="row">
		<div class="jumbotron col-md-12">
			<div class="container">
				<h1>Hola, world!</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio in possimus natus doloremque minus dicta, rem quidem alias facere a provident magni, delectus necessitatibus? Ratione dolorum aliquid et? Reiciendis, consectetur.</p>
				<p>
					<a class="btn btn-primary btn-lg" href="#" role="button"> Learn more</a>
				</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="page-header">
				<h1>Example page header <small>Subtext for header</small></h1>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id esse, fuga. Quaerat quod ducimus ad ratione consequuntur ipsum. Similique, rerum hic fugiat amet rem magni eaque aliquam tenetur, aliquid at.</p>
		</div>

		<div class="col-md-4">
			<div class="page-header">
				<h1>Example page header <small>Subtext for header</small></h1>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id esse, fuga. Quaerat quod ducimus ad ratione consequuntur ipsum. Similique, rerum hic fugiat amet rem magni eaque aliquam tenetur, aliquid at.</p>
		</div>

		<div class="col-md-4">
			<div class="page-header">
				<h1>Example page header <small>Subtext for header</small></h1>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id esse, fuga. Quaerat quod ducimus ad ratione consequuntur ipsum. Similique, rerum hic fugiat amet rem magni eaque aliquam tenetur, aliquid at.</p>
		</div>

	</div>
</div>

app/views/main/mypublications.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Mis Publicaciones</h1>

  <% @publications.each do |publication| %>
  <div class="col-md-3">
    <div class="thumbnail">
      <%= publication.title %>
      <%= image_tag(publication.photo, :class => 'img-responsive') %>
      <%= publication.address %>
      <%= publication.description %> 
      <br>
      <%= publication.telephone %>
      
      <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        <%= link_to 'Show', publication, :class => 'btn' %>
        <%= link_to 'Edit', edit_publication_path(publication), :class => 'btn' %>
        <% if user_signed_in? %>
          <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>

    </div>
  </div>
  <% end %>

  <br>
  
  <% if user_signed_in? %>
    <%= link_to 'Crear una Publicación', new_publication_path %>
  <% end %>
</div>

app/views/main/publicof.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Mis Publicaciones</h1>

  <% @publications.each do |publication| %>
  <div class="col-md-3">
    <div class="thumbnail">
      <%= publication.title %>
      <%= image_tag(publication.photo, :class => 'img-responsive') %>
      <%= publication.address %>
      <%= publication.description %> 
      <br>
      <%= publication.telephone %>
      
      <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        <%= link_to 'Show', publication, :class => 'btn' %>
        <%= link_to 'Edit', edit_publication_path(publication), :class => 'btn' %>
        <% if user_signed_in? %>
          <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>

    </div>
  </div>
  <% end %>

  <br>
  
  <% if user_signed_in? %>
    <%= link_to 'Crear una Publicación', new_publication_path %>
  <% end %>
</div>

app/views/main/somos.html.erb
<h1>Main#somos</h1>
<p>Find me in app/views/main/somos.html.erb</p>

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
<% if @publication.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

  <ul>
    <% @publication.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <div class="field">
    <%= f.label :title, "Nombre" %><br>
    <%= f.text_field :title, :class => 'form-control', :placeholder => "Ingresa un título" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :photo, "Foto" %><br>
    <%= f.text_field :photo, :class => 'form-control', :placeholder => "Ingresa una imagen" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :address, "Dirección" %><br>
    <%= f.text_field :address, :class => 'form-control', :placeholder => "Ingresa una dirección" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :telephone, "Teléfono" %><br>
    <%= f.text_field :telephone, :class => 'form-control', :placeholder => "Ingresa un teléfono" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_area :description, :class => 'form-control', :placeholder => "Ingresa una descripción", :rows => "6", :cols => "30" %>
  </div>
</div>

<div class="actions">
  <%= f.submit "Crear", :class => "btn btn-primary" %>
</div>
<% end %>

app/views/publications/edit.html.erb
<div class="container">
	<h1>Editar Publicación</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
	<%= link_to 'Show', @publication %> |
	<%= link_to 'Back', publications_path %>
</div>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Lista de Publicaciones</h1>

  <% @publications.each do |publication| %>
  <div class="col-md-3">
    <div class="thumbnail">
      <%= publication.title %>
      <%= image_tag(publication.photo, :class => 'img-responsive') %>
      <%= publication.address %>
      <%= publication.description %> 
      <br>
      <%= publication.telephone %>
      
      <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        <%= link_to 'Show', publication, :class => 'btn' %>
        <%= link_to 'Edit', edit_publication_path(publication), :class => 'btn' %>
        <% if user_signed_in? %>
          <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>

    </div>
  </div>
  <% end %>

  <br>
  
  <% if user_signed_in? %>
    <%= link_to 'Crear una Publicación', new_publication_path %>
  <% end %>
</div>

app/views/publications/new.html.erb
<div class="container">
	<h1>Nueva Publicación</h1>
	
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>

	<%= link_to 'Back', publications_path %>
</div>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@publication.photo) %>
</p>

<p>
  <strong>Address:</strong>
  <%= @publication.address %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @publication.telephone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publication.description %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %> | 
<%= link_to 'Más publicaciones del mismo usuario', publicof_path(@publication.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= main_index_path %>">Mi Marca</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="<%= publications_path %>">Publicaciones</a></li>
				<li><a href="<%= mypublications_path %>">Mis Publicaciones</a></li>
				<li><a href="<%= new_publication_path %>">Crear nueva Publicación</a></li>
				<li><a href="<%= main_somos_path %>">Nosotros</a></li>
				<li><a href="<%= main_contacto_path %>">Contacto</a></li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<% if current_user.nil? %>
				<li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
				<li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
				<% else %>
				<li><a href="<%= destroy_user_session_path %>" data-method="DELETE">Cerrar Sesión</a></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>